export const results = {
  "nhits": 8,
  "parameters": {
    "dataset": "airbnb-listings",
    "timezone": "UTC",
    "rows": 10,
    "start": 0,
    "format": "json"
  },
  "records": [
    {
      "datasetid": "airbnb-listings",
      "recordid": "afc54fdfcc898d4f38d92769cb930c444e574f9d",
      "fields": {
        "review_scores_accuracy": 10,
        "reviews_per_month": 2.1,
        "bathrooms": 2,
        "first_review": "2016-10-13",
        "geolocation": [
          51.502480414873446,
          0.0008590198259377014
        ],
        "cancellation_policy": "strict",
        "transit": "North Greenwich Jubilee line station is a 5 min walk away, allows you easy access into Central London (Bond Street is under 20 mins away on the Jubilee line). Greenwich Pier is right next to the O2, where you may catch the river bus, and take a more scenic route through London, stopping at all the major sights including Canary Wharf, Tower Bridge, Westminster and the London Eye. There is also the cable car from North Greenwich terminal which takes you over to Royal Victoria and the Excel Centre.",
        "accommodates": 6,
        "calendar_last_scraped": "2017-03-04",
        "medium_url": "https://a0.muscache.com/im/pictures/00b5c915-5479-4a0e-8ec4-4ebdc56307da.jpg?aki_policy=medium",
        "host_neighbourhood": "LB of Newham",
        "street": "Waterview Drive, London, England SE10 0AX, United Kingdom",
        "last_scraped": "2017-03-04",
        "calendar_updated": "today",
        "country_code": "GB",
        "review_scores_cleanliness": 10,
        "neighborhood_overview": "The apartment is right next to the O2, so perfect for anyone attending events or exhibitions there. The O2 is packed with a great range of restaurants and bars to suit all taste buds! It boasts the largest cinema screen in Europe.",
        "availability_365": 59,
        "id": "14994653",
        "market": "London",
        "features": "Host Is Superhost,Host Has Profile Pic,Host Identity Verified,Is Location Exact",
        "city": "London",
        "property_type": "Apartment",
        "space": "Stunning, brand new apartment with great unobstructed view over the Thames overlooking Canary Wharf. It is west facing so you get a lovely view of the sunset. The apartment is interlinked to the Intercontinental hotel, so you will have full use of the gym and spa and have room service available from the hotel restaurant. The apartment building is connected to the O2 allowing you to walk directly into the O2. Open Plan Living Area & Kitchen - spacious open plan living room with full sized double sofa bed - fully equipped modern kitchen with a washer dryer and dish washer. Includes crockery and cutlery to make life easier for our guests! - riverside balcony Dining Room - separate dining room seating 6 Room 1 - en suite master bedroom with a double bed - large modern wardrobe with lots of space to hang up your clothes - beautiful floor standing mirror - a reading corner with a comfy armchair Room 2 - good sized second bedroom with a double bed - large modern wardrobe with lots of space",
        "availability_60": 39,
        "picture_url": {
          "mimetype": "image/jpeg",
          "format": "JPEG",
          "color_summary": [
            "rgba(212, 213, 206, 1.00)",
            "rgba(185, 192, 185, 1.00)",
            "rgba(134, 126, 115, 1.00)"
          ],
          "filename": "00b5c915-5479-4a0e-8ec4-4ebdc56307da.jpg",
          "width": 639,
          "id": "c6dddb7c1a9113ae1c36c563ac13c20e",
          "height": 426,
          "thumbnail": true
        },
        "zipcode": "SE10 0AX",
        "host_location": "London, United Kingdom",
        "access": "Guests have full access to the entire property, facilities are not shared with other guests. Normal check-in is from 3pm. Depending on the availability of the apartment, we are happy to accommodate an earlier check-in. Please check with us before arrival.",
        "availability_90": 59,
        "state": "England",
        "thumbnail_url": "https://a0.muscache.com/im/pictures/00b5c915-5479-4a0e-8ec4-4ebdc56307da.jpg?aki_policy=small",
        "amenities": "TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Pool,Kitchen,Gym,Breakfast,Elevator in building,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace",
        "security_deposit": 250,
        "maximum_nights": 1125,
        "review_scores_value": 10,
        "latitude": "51.502480414873446",
        "review_scores_location": 10,
        "house_rules": "Strictly no parties or functions. Strictly no extra guests to be brought into the apartment without permission. Noise to be kept down after 11pm. Please do not speak to the building management or concierge, i can be reached at any time to deal with any issues. Check-ins between 8PM and 12AM incur an additional charge of £30 Check-ins after 12AM incur an additional charge of £60 Check-out is at 11am unless previously arranged with us. Unauthorised late check-outs will incur a fee of £20 per hour for a maximum of 3 hours. After 2pm the full day rate will be charged. Parking fees apply and must be pre arranged.",
        "host_since": "2014-04-20",
        "listing_url": "https://www.airbnb.com/rooms/14994653",
        "bedrooms": 2,
        "description": "Our beautiful new 2 bedroom apartment overlooks the river with a stunning view of the London skyline. It is a perfect base for events at the O2 Arena, a 2 min walk. The ExCel centre is 20 mins away and you have excellent links into central London. The apartment is brand new with a spacious living area, lots of natural light and a lovely balcony. It is fully equipped to ensure that you are comfortable and have everything you need to feel at home. It is suitable for family and groups. Stunning, brand new apartment with great unobstructed view over the Thames overlooking Canary Wharf. It is west facing so you get a lovely view of the sunset. The apartment is interlinked to the Intercontinental hotel, so you will have full use of the gym and spa and have room service available from the hotel restaurant. The apartment building is connected to the O2 allowing you to walk directly into the O2. Open Plan Living Area & Kitchen - spacious open plan living room with full sized double sofa bed",
        "review_scores_communication": 10,
        "experiences_offered": "none",
        "price": 250,
        "host_picture_url": "https://a0.muscache.com/im/pictures/73f75806-3e64-4df1-97a1-48a5cacacbfd.jpg?aki_policy=profile_x_medium",
        "extra_people": 15,
        "smart_location": "London, United Kingdom",
        "last_review": "2017-02-12",
        "host_verifications": "email,phone,reviews,jumio",
        "number_of_reviews": 10,
        "host_response_rate": 100,
        "minimum_nights": 2,
        "host_about": "As the founder of Wild Roses, a specialist property management company, I go above and beyond to ensure all my guests have a stay they will remember. I have been hosting for over 3 years and constantly look for ways to improve the experience for my guests in both my own listings and the listings I manage for other hosts. I love to travel and have a keen interest in history mostly through exploring ancient architecture. I almost always enjoy the food! I love great conversations and gravitate towards those that inspire me, who are pushing the boundaries in doing better in love, life and laughter. I'm passionate about hospitality and happy to go the extra mile to ensure my guests have a memorable stay.",
        "guests_included": 4,
        "host_url": "https://www.airbnb.com/users/show/14517363",
        "host_id": "14517363",
        "availability_30": 23,
        "host_total_listings_count": 20,
        "neighbourhood": "Greenwich",
        "calculated_host_listings_count": 10,
        "interaction": "We will welcome you at check-in and you may get in touch anytime you need any assistance via my mobile or AirBnB.",
        "name": "Perfect location for O2 Events & Concerts, London",
        "neighbourhood_cleansed": "Greenwich",
        "bed_type": "Real Bed",
        "host_listings_count": 20,
        "host_response_time": "within an hour",
        "longitude": "0.0008590198259377014",
        "summary": "Our beautiful new 2 bedroom apartment overlooks the river with a stunning view of the London skyline. It is a perfect base for events at the O2 Arena, a 2 min walk. The ExCel centre is 20 mins away and you have excellent links into central London. The apartment is brand new with a spacious living area, lots of natural light and a lovely balcony. It is fully equipped to ensure that you are comfortable and have everything you need to feel at home. It is suitable for family and groups.",
        "beds": 3,
        "host_thumbnail_url": "https://a0.muscache.com/im/pictures/73f75806-3e64-4df1-97a1-48a5cacacbfd.jpg?aki_policy=profile_small",
        "xl_picture_url": "https://a0.muscache.com/im/pictures/00b5c915-5479-4a0e-8ec4-4ebdc56307da.jpg?aki_policy=x_large",
        "cleaning_fee": 50,
        "host_name": "Adeel",
        "country": "United Kingdom",
        "scrape_id": "20170304065726",
        "review_scores_rating": 98,
        "review_scores_checkin": 10,
        "room_type": "Entire home/apt"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          0.0008590198259377014,
          51.502480414873446
        ]
      },
      "record_timestamp": "2020-08-02T17:09:33.658000+00:00"
    },
    {
      "datasetid": "airbnb-listings",
      "recordid": "36a6a25479f098b559e8359a970d3d9248e126df",
      "fields": {
        "review_scores_accuracy": 10,
        "reviews_per_month": 0.65,
        "bathrooms": 3,
        "first_review": "2016-10-18",
        "geolocation": [
          51.55626466422855,
          -0.19258040809343402
        ],
        "cancellation_policy": "moderate",
        "accommodates": 6,
        "calendar_last_scraped": "2017-03-04",
        "neighbourhood_cleansed": "Camden",
        "host_neighbourhood": "Notting Hill",
        "street": "Kidderpore Avenue, London, NW3 7SF, United Kingdom",
        "review_scores_communication": 10,
        "calendar_updated": "4 weeks ago",
        "country_code": "GB",
        "review_scores_cleanliness": 10,
        "property_type": "Apartment",
        "availability_365": 359,
        "id": "10766030",
        "market": "London",
        "features": "Host Is Superhost,Host Has Profile Pic,Host Identity Verified,Is Location Exact",
        "city": "London",
        "availability_60": 60,
        "picture_url": {
          "mimetype": "image/jpeg",
          "format": "JPEG",
          "color_summary": [
            "rgba(166, 179, 201, 1.00)",
            "rgba(193, 164, 144, 1.00)",
            "rgba(46, 27, 18, 1.00)"
          ],
          "filename": "dd44889e-37f5-4bb9-bbc1-22ecbdc13eb4.jpg",
          "width": 360,
          "id": "9a2cade0834f3facfa32ecfd2d1a3db9",
          "height": 426,
          "thumbnail": true
        },
        "zipcode": "NW3 7SF",
        "host_location": "London",
        "availability_90": 90,
        "amenities": "TV,Cable TV,Internet,Wireless Internet,Wheelchair accessible,Pool,Kitchen,Doorman,Gym,Breakfast,Elevator in building,Buzzer/wireless intercom,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,First aid kit,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace",
        "host_listings_count": 4,
        "maximum_nights": 1125,
        "listing_url": "https://www.airbnb.com/rooms/10766030",
        "latitude": "51.55626466422855",
        "review_scores_location": 10,
        "review_scores_checkin": 10,
        "host_since": "2014-01-25",
        "bedrooms": 3,
        "description": "This is a home away from home 3 bedrooms 2 ensuite and the use of an on site amazing Gym and Swimming Pool. Close to the excellent transport links of West Hampstead and the village like feel of West End Lane.This is a slice of heaven on earth!",
        "experiences_offered": "none",
        "price": 250,
        "host_picture_url": "https://a0.muscache.com/im/users/11621858/profile_pic/1400839298/original.jpg?aki_policy=profile_x_medium",
        "extra_people": 0,
        "smart_location": "London, United Kingdom",
        "last_review": "2017-01-14",
        "host_verifications": "email,phone,facebook,reviews,jumio,government_id",
        "number_of_reviews": 3,
        "host_response_rate": 100,
        "host_about": "Love London living especially the area around Portobello Road in Notting Hill.Great food great community. Favorite travel destinations are LA, Ibiza and Koi Samui",
        "guests_included": 1,
        "host_url": "https://www.airbnb.com/users/show/11621858",
        "host_id": "11621858",
        "availability_30": 30,
        "host_total_listings_count": 4,
        "neighbourhood": "Hampstead",
        "calculated_host_listings_count": 4,
        "name": "3 bed Flat in NW3 Amazing View/Pool",
        "bed_type": "Real Bed",
        "country": "United Kingdom",
        "host_response_time": "within an hour",
        "longitude": "-0.19258040809343402",
        "summary": "This is a home away from home 3 bedrooms 2 ensuite and the use of an on site amazing Gym and Swimming Pool. Close to the excellent transport links of West Hampstead and the village like feel of West End Lane.This is a slice of heaven on earth!",
        "beds": 3,
        "minimum_nights": 1,
        "review_scores_value": 10,
        "cleaning_fee": 160,
        "host_name": "Mel",
        "last_scraped": "2017-03-04",
        "scrape_id": "20170304065726",
        "review_scores_rating": 100,
        "host_thumbnail_url": "https://a0.muscache.com/im/users/11621858/profile_pic/1400839298/original.jpg?aki_policy=profile_small",
        "room_type": "Entire home/apt"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.19258040809343402,
          51.55626466422855
        ]
      },
      "record_timestamp": "2020-08-02T17:09:33.658000+00:00"
    },
    {
      "datasetid": "airbnb-listings",
      "recordid": "79b232810190b196702431d683f7769734a6ccba",
      "fields": {
        "review_scores_accuracy": 10,
        "reviews_per_month": 8.09,
        "bathrooms": 1,
        "first_review": "2016-12-06",
        "geolocation": [
          51.52902627717578,
          -0.0907459903493859
        ],
        "cancellation_policy": "strict",
        "accommodates": 2,
        "calendar_last_scraped": "2017-03-04",
        "medium_url": "https://a0.muscache.com/im/pictures/46407cc5-c364-4bfb-b290-dab42e2b3058.jpg?aki_policy=medium",
        "street": "City Road, London, England EC1V 1AQ, United Kingdom",
        "review_scores_communication": 10,
        "calendar_updated": "2 days ago",
        "country_code": "GB",
        "review_scores_cleanliness": 9,
        "property_type": "Apartment",
        "availability_365": 2,
        "id": "16038129",
        "market": "London",
        "features": "Host Is Superhost,Host Has Profile Pic,Host Identity Verified",
        "city": "London",
        "availability_60": 0,
        "picture_url": {
          "mimetype": "image/jpeg",
          "format": "JPEG",
          "color_summary": [
            "rgba(216, 215, 212, 1.00)",
            "rgba(142, 139, 133, 1.00)",
            "rgba(54, 48, 42, 1.00)"
          ],
          "filename": "46407cc5-c364-4bfb-b290-dab42e2b3058.jpg",
          "width": 639,
          "id": "755e99da0ac86d168f59cdb99a342e0d",
          "height": 426,
          "thumbnail": true
        },
        "zipcode": "EC1V 1AQ",
        "host_location": "London",
        "access": "The entire flat and the gym and spa facilities",
        "availability_90": 0,
        "state": "England",
        "thumbnail_url": "https://a0.muscache.com/im/pictures/46407cc5-c364-4bfb-b290-dab42e2b3058.jpg?aki_policy=small",
        "amenities": "Internet,Pool,Kitchen,Gym,Elevator in building,Heating,Family/kid friendly,Washer,Smoke detector,Shampoo,Hangers",
        "security_deposit": 200,
        "maximum_nights": 1125,
        "review_scores_value": 10,
        "latitude": "51.52902627717578",
        "review_scores_location": 10,
        "host_listings_count": 1,
        "host_since": "2014-03-11",
        "listing_url": "https://www.airbnb.com/rooms/16038129",
        "bedrooms": 1,
        "description": "One bedroom flat in modern new build with gym, spa, sauna, steamroom. Close to all the amenities of Old St and Shoreditch and a 4 mins walk to Old St tube station. Discounts apply for longer stays! The entire flat and the gym and spa facilities As often as needed.",
        "experiences_offered": "none",
        "price": 65,
        "host_picture_url": "https://a0.muscache.com/im/pictures/f414dc2f-638a-45cf-bfb0-db657f47e97c.jpg?aki_policy=profile_x_medium",
        "extra_people": 0,
        "smart_location": "London, United Kingdom",
        "last_review": "2017-03-03",
        "host_verifications": "email,phone,reviews,jumio",
        "number_of_reviews": 24,
        "host_response_rate": 100,
        "minimum_nights": 1,
        "host_about": "Love travelling, friends, going out :)",
        "guests_included": 1,
        "host_url": "https://www.airbnb.com/users/show/13026637",
        "host_id": "13026637",
        "availability_30": 0,
        "host_total_listings_count": 1,
        "calculated_host_listings_count": 1,
        "interaction": "As often as needed.",
        "name": "Modern flat in Old St Shoreditch",
        "neighbourhood_cleansed": "Hackney",
        "bed_type": "Real Bed",
        "country": "United Kingdom",
        "host_response_time": "within an hour",
        "longitude": "-0.0907459903493859",
        "summary": "One bedroom flat in modern new build with gym, spa, sauna, steamroom. Close to all the amenities of Old St and Shoreditch and a 4 mins walk to Old St tube station. Discounts apply for longer stays!",
        "beds": 1,
        "host_thumbnail_url": "https://a0.muscache.com/im/pictures/f414dc2f-638a-45cf-bfb0-db657f47e97c.jpg?aki_policy=profile_small",
        "xl_picture_url": "https://a0.muscache.com/im/pictures/46407cc5-c364-4bfb-b290-dab42e2b3058.jpg?aki_policy=x_large",
        "cleaning_fee": 10,
        "host_name": "Wen",
        "last_scraped": "2017-03-04",
        "scrape_id": "20170304065726",
        "review_scores_rating": 95,
        "review_scores_checkin": 10,
        "room_type": "Entire home/apt"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.0907459903493859,
          51.52902627717578
        ]
      },
      "record_timestamp": "2020-08-02T17:09:33.658000+00:00"
    },
    {
      "datasetid": "airbnb-listings",
      "recordid": "4c5a1908289d3a0e5fe49b57cc0daeaeaffbb67f",
      "fields": {
        "review_scores_accuracy": 10,
        "reviews_per_month": 1.77,
        "bathrooms": 2,
        "first_review": "2015-08-26",
        "geolocation": [
          51.49541510941703,
          -0.20113351726923487
        ],
        "cancellation_policy": "strict",
        "transit": "You will be 8 minutes walk from Earls Court tube station and 10 minutes from High Street Kensington tube. The key buses are No. 9 to Piccadilly and the West End via Knightsbridge and No. 10 to Oxford Street via Knightsbridge and Marble Arch.",
        "accommodates": 4,
        "calendar_last_scraped": "2017-03-04",
        "medium_url": "https://a0.muscache.com/im/pictures/101345312/2d58f0ec_original.jpg?aki_policy=medium",
        "host_neighbourhood": "Kensington",
        "street": "Huntsmore House, 35 Pembroke Road, London, W8 6LZ, United Kingdom",
        "last_scraped": "2017-03-05",
        "calendar_updated": "2 weeks ago",
        "country_code": "GB",
        "review_scores_cleanliness": 10,
        "neighborhood_overview": "Our apartment in Kensington is 3 minutes walk from the vibrant and fashionable High Street Kensington and Holland Park. It is bordered to the north by Notting Hill and the south by South Kensington and Chelsea. Foodies will love the array of restaurants within walking distance. Most of London's key museums are within easy reach.",
        "availability_365": 20,
        "id": "7528989",
        "market": "London",
        "features": "Host Is Superhost,Host Has Profile Pic,Host Identity Verified,Is Location Exact,Instant Bookable",
        "city": "London",
        "property_type": "Apartment",
        "space": "The 40sqm Reception Room with a marble dining table, lounge area and double desk station is spacious, bright and boasts a balcony. The Mater Bedroom features an Poliform Arca 6ft Super King Bed with two individual duvets to give you and your partner a good night's sleep. The room's Poliform Capri four door wardrobe ensures your stay is stylish and uncluttered. The Master Bedroom's Ensuite Bathroom includes a large shower. The Second Bedroom has two single beds, a child's cot as well as fitted wardrobes and a chest of drawers. The Second Bathroom includes a bath with a shower.",
        "availability_60": 0,
        "picture_url": {
          "mimetype": "image/jpeg",
          "format": "JPEG",
          "color_summary": [
            "rgba(197, 193, 186, 1.00)",
            "rgba(175, 174, 171, 1.00)",
            "rgba(186, 164, 133, 1.00)"
          ],
          "filename": "2d58f0ec_original.jpg",
          "width": 719,
          "id": "0c9abb9700911da6e08af470636b9c09",
          "height": 480,
          "thumbnail": true
        },
        "zipcode": "W8 6LZ",
        "host_since": "2015-07-16",
        "host_location": "London, England, United Kingdom",
        "access": "Entire apartment, balcony, pool, gym, sauna and internal gardens.",
        "availability_90": 0,
        "review_scores_value": 10,
        "thumbnail_url": "https://a0.muscache.com/im/pictures/101345312/2d58f0ec_original.jpg?aki_policy=small",
        "amenities": "TV,Internet,Wireless Internet,Wheelchair accessible,Pool,Kitchen,Doorman,Gym,Elevator in building,Buzzer/wireless intercom,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,First aid kit,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace",
        "security_deposit": 250,
        "maximum_nights": 360,
        "listing_url": "https://www.airbnb.com/rooms/7528989",
        "latitude": "51.49541510941703",
        "review_scores_location": 10,
        "house_rules": "1. No pets allowed (as building rules don't allow it); 2. No smoking please. You may smoke on the balcony but please keep glass doors shut. 3. No parties please. 4. Please do not move dining table as it is an extremely heavy.",
        "monthly_price": 4290,
        "bedrooms": 2,
        "description": "Located in Kensington, our newly renovated 2-bedroom, 2-bathroom 100sqm apartment with spacious and smart interiors is an ideal home base for London culture, shopping and business. Our pool, gym, sauna and porter all add to your relaxing stay. The 40sqm Reception Room with a marble dining table, lounge area and double desk station is spacious, bright and boasts a balcony. The Mater Bedroom features an Poliform Arca 6ft Super King Bed with two individual duvets to give you and your partner a good night's sleep. The room's Poliform Capri four door wardrobe ensures your stay is stylish and uncluttered. The Master Bedroom's Ensuite Bathroom includes a large shower. The Second Bedroom has two single beds, a child's cot as well as fitted wardrobes and a chest of drawers. The Second Bathroom includes a bath with a shower. Entire apartment, balcony, pool, gym, sauna and internal gardens. You will of course be welcome at check-in and attended to at check out. We can be contacted during your s",
        "review_scores_communication": 10,
        "experiences_offered": "none",
        "price": 202,
        "host_picture_url": "https://a0.muscache.com/im/users/38684143/profile_pic/1440427428/original.jpg?aki_policy=profile_x_medium",
        "extra_people": 50,
        "smart_location": "London, United Kingdom",
        "last_review": "2017-02-13",
        "host_verifications": "email,phone,reviews,jumio",
        "number_of_reviews": 33,
        "host_response_rate": 100,
        "minimum_nights": 5,
        "host_about": "I'm married with 2 boys under 3 but don't worry you have exclusive use of the flat. I'm in finance/principal investing. We live abroad but a lovely lady Kristine will welcome you for your stay. Enjoy London!",
        "guests_included": 4,
        "host_url": "https://www.airbnb.com/users/show/38684143",
        "host_id": "38684143",
        "availability_30": 0,
        "host_total_listings_count": 1,
        "neighbourhood": "Kensington",
        "calculated_host_listings_count": 1,
        "interaction": "You will of course be welcome at check-in and attended to at check out. We can be contacted during your stay and the porter will also be very helpful if you have questions during your stay. You have use of the entire apartment.",
        "name": "Lux 2Bed, 2Bath, Pool, Gym, Porter",
        "neighbourhood_cleansed": "Kensington and Chelsea",
        "bed_type": "Real Bed",
        "host_listings_count": 1,
        "host_response_time": "within an hour",
        "longitude": "-0.20113351726923487",
        "summary": "Located in Kensington, our newly renovated 2-bedroom, 2-bathroom 100sqm apartment with spacious and smart interiors is an ideal home base for London culture, shopping and business. Our pool, gym, sauna and porter all add to your relaxing stay.",
        "beds": 3,
        "host_thumbnail_url": "https://a0.muscache.com/im/users/38684143/profile_pic/1440427428/original.jpg?aki_policy=profile_small",
        "xl_picture_url": "https://a0.muscache.com/im/pictures/101345312/2d58f0ec_original.jpg?aki_policy=x_large",
        "cleaning_fee": 85,
        "host_name": "Benson",
        "country": "United Kingdom",
        "scrape_id": "20170304065726",
        "review_scores_rating": 98,
        "review_scores_checkin": 10,
        "room_type": "Entire home/apt"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.20113351726923487,
          51.49541510941703
        ]
      },
      "record_timestamp": "2020-08-02T17:09:33.658000+00:00"
    },
    {
      "datasetid": "airbnb-listings",
      "recordid": "c6db1ab02c1d6fd18ee9116896e041458a8a9683",
      "fields": {
        "review_scores_accuracy": 10,
        "reviews_per_month": 0.49,
        "bathrooms": 1,
        "first_review": "2014-06-24",
        "geolocation": [
          51.51459314939833,
          -0.1375192101095003
        ],
        "cancellation_policy": "strict",
        "transit": "5-10 min walk from various metro stations: Oxford Circus, Tottenham Court, Picaddilly, leicester square, Covent garden.",
        "accommodates": 2,
        "calendar_last_scraped": "2017-03-05",
        "medium_url": "https://a0.muscache.com/im/pictures/29752670/ad3e2e1f_original.jpg?aki_policy=medium",
        "host_neighbourhood": "Soho",
        "street": "Dufours Place, London, England W1F 7 SH, United Kingdom",
        "review_scores_communication": 10,
        "calendar_updated": "today",
        "country_code": "GB",
        "review_scores_cleanliness": 9,
        "neighborhood_overview": "You are in the middle of Soho theatreland, Oxford street shopping and Picadilly circus. Central London, also called the West-end. Upscale West End includes the Theatre district. Leicester and Trafalgar square, are right on your door step. Within a block are shopping areas of Oxford Carnaby street, elegant Old Bond street, art galleries trendy cafés of Old Compton’s street and Berwick street food market. Best food stores within 5-10 min walk: Wholefoods, Waitrose, Marks & Spencer",
        "availability_365": 206,
        "id": "2202826",
        "market": "London",
        "features": "Host Is Superhost,Host Has Profile Pic,Host Identity Verified,Is Location Exact",
        "city": "London",
        "property_type": "Apartment",
        "space": "AMENITIES: •Desk with broadband internet hookup & WIFI, and telephone, stereo, radio, Ipod player •Luxury bathroom with ultra big modern shower room: big rain shower head, heated towelrack •Fully equipped stylish open-plan kitchen: microwave, oven, induction plates, dishwasher, washer and dryer, cutlery, utensils, large fridge, all essentials for cooking •Glass bar for 2 overlooking London, dining table for 4-6 in the living •Spacious master bedroom: huge King-size bed with Tempur deluxe mattress, 30-inch TV scree(URL HIDDEN)Storage cupboards, deluxe cotton sheets, plenty of egyptian cotton towel sets A Leisure centre is situated on Marshall street at the back of our building block. It features an art deco 30m pool, spa and fitness room; access is possible for a small daily fee, for example, the pool costs about 6£ per day. There is also a gardened terrace on 3d floor for use of residents only. This flat offers upscale living in the most central part of London. It serves a",
        "availability_60": 20,
        "picture_url": {
          "mimetype": "image/jpeg",
          "format": "JPEG",
          "color_summary": [
            "rgba(213, 228, 241, 1.00)",
            "rgba(156, 154, 152, 1.00)",
            "rgba(108, 106, 103, 1.00)"
          ],
          "filename": "ad3e2e1f_original.jpg",
          "width": 639,
          "id": "8fc31d6d6f8bb65821492be6842b2eb6",
          "height": 426,
          "thumbnail": true
        },
        "zipcode": "W1F 7 SH",
        "host_since": "2014-01-12",
        "host_location": "Klundert, North Brabant, Netherlands",
        "access": "You are in the middle of Soho theatreland, Oxford street shopping and Picadilly circus",
        "availability_90": 20,
        "state": "England",
        "thumbnail_url": "https://a0.muscache.com/im/pictures/29752670/ad3e2e1f_original.jpg?aki_policy=small",
        "amenities": "TV,Cable TV,Internet,Wireless Internet,Wheelchair accessible,Pool,Kitchen,Doorman,Gym,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Dryer,Smoke detector,First aid kit,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace",
        "security_deposit": 900,
        "maximum_nights": 45,
        "review_scores_value": 9,
        "latitude": "51.51459314939833",
        "review_scores_location": 10,
        "host_listings_count": 1,
        "monthly_price": 3900,
        "listing_url": "https://www.airbnb.com/rooms/2202826",
        "bedrooms": 1,
        "description": "Luxury, large PENTHOUSE flat in SOHO with spectacular PANORAMIC VIEWS. TOP floor Modern High-rise. Huge windows give lots of light, overlooking the City, Oxford st and Mayfair. THE very heart of London. Luxury amenities, Kingsize bed, Big screenTV AMENITIES: •Desk with broadband internet hookup & WIFI, and telephone, stereo, radio, Ipod player •Luxury bathroom with ultra big modern shower room: big rain shower head, heated towelrack •Fully equipped stylish open-plan kitchen: microwave, oven, induction plates, dishwasher, washer and dryer, cutlery, utensils, large fridge, all essentials for cooking •Glass bar for 2 overlooking London, dining table for 4-6 in the living •Spacious master bedroom: huge King-size bed with Tempur deluxe mattress, 30-inch TV scree(URL HIDDEN)Storage cupboards, deluxe cotton sheets, plenty of egyptian cotton towel sets A Leisure centre is situated on Marshall street at the back of our building block. It features an art deco 30m pool, spa and fitnes",
        "experiences_offered": "none",
        "price": 149,
        "host_picture_url": "https://a0.muscache.com/im/pictures/cdd87da5-1a72-42de-93f0-f5b7d53ea365.jpg?aki_policy=profile_x_medium",
        "extra_people": 0,
        "smart_location": "London, United Kingdom",
        "last_review": "2017-02-12",
        "host_verifications": "email,phone,reviews,jumio",
        "number_of_reviews": 16,
        "host_response_rate": 100,
        "minimum_nights": 3,
        "host_response_time": "within an hour",
        "guests_included": 1,
        "host_url": "https://www.airbnb.com/users/show/11238220",
        "host_id": "11238220",
        "availability_30": 8,
        "host_total_listings_count": 1,
        "neighbourhood": "Soho",
        "calculated_host_listings_count": 1,
        "interaction": "I am available on email and our caretaker lives nearby, greets our guests and is available during your stay.",
        "name": "DELUXE PENTHOUSE SOHO City views",
        "neighbourhood_cleansed": "Westminster",
        "bed_type": "Real Bed",
        "country": "United Kingdom",
        "notes": "It serves as owner’s pied-à-terre when in London. Therefore I improve the place all the time with new amenities. Refurbishment: Brand-new appliances, leather furniture and contemporary designer fixtures.",
        "longitude": "-0.1375192101095003",
        "summary": "Luxury, large PENTHOUSE flat in SOHO with spectacular PANORAMIC VIEWS. TOP floor Modern High-rise. Huge windows give lots of light, overlooking the City, Oxford st and Mayfair. THE very heart of London. Luxury amenities, Kingsize bed, Big screenTV",
        "beds": 1,
        "host_thumbnail_url": "https://a0.muscache.com/im/pictures/cdd87da5-1a72-42de-93f0-f5b7d53ea365.jpg?aki_policy=profile_small",
        "xl_picture_url": "https://a0.muscache.com/im/pictures/29752670/ad3e2e1f_original.jpg?aki_policy=x_large",
        "cleaning_fee": 80,
        "host_name": "Paul",
        "last_scraped": "2017-03-05",
        "scrape_id": "20170304065726",
        "review_scores_rating": 93,
        "review_scores_checkin": 9,
        "room_type": "Entire home/apt"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.1375192101095003,
          51.51459314939833
        ]
      },
      "record_timestamp": "2020-08-02T17:09:33.658000+00:00"
    },
    {
      "datasetid": "airbnb-listings",
      "recordid": "a205411b748e039d167e741259c74ac9fa527d81",
      "fields": {
        "review_scores_accuracy": 10,
        "reviews_per_month": 0.95,
        "bathrooms": 1,
        "first_review": "2014-04-29",
        "geolocation": [
          51.47526359086135,
          -0.18427740690654582
        ],
        "cancellation_policy": "strict",
        "transit": "Imperial Wharf Station is seconds away for the overground train in and out of London; the River Bus at Chelsea Harbour is a great way to get into the centre of town, City of London & East London; the underground is a 10 minute walk away at Fulham Broadway; there is a bus stop right outside for local routes; plus Transport for London 'Santandar Cycles' have bikes available right outside the apartment. It is easy to get a black taxi by Imperial Wharf as they go through Chelsea Harbour day & night. Or you can book a taxi with Addison Lee on (PHONE NUMBER HIDDEN).",
        "accommodates": 2,
        "calendar_last_scraped": "2017-03-04",
        "medium_url": "https://a0.muscache.com/im/pictures/35648182/587f3361_original.jpg?aki_policy=medium",
        "host_neighbourhood": "Sands End",
        "street": "Park Street, London, SW6 2FL, United Kingdom",
        "last_scraped": "2017-03-05",
        "calendar_updated": "3 days ago",
        "country_code": "GB",
        "review_scores_cleanliness": 10,
        "neighborhood_overview": "A great modern luxury apartment in the heart of the Design Centre of Chelsea Harbour, close to the Kings Road and all the amenities of Chelsea with great transport links in and out of London. There is a supermarket and coffee shop within the wider development and the infamous Blue Elephant restaurant.",
        "availability_365": 103,
        "id": "2682093",
        "market": "London",
        "features": "Host Is Superhost,Host Has Profile Pic,Host Identity Verified,Is Location Exact,Instant Bookable",
        "city": "London",
        "property_type": "Apartment",
        "space": "A spectacular newly completed 4th floor (of five) Manhattan style apartment overlooking the quiet well maintained communal gardens designed by award-winning gardener. The accommodation offers a good size open plan living room with modern kitchen, access to a 40 square foot private balcony, a double bedroom with fitted wardrobes and en-suite shower room. This high-end apartment is part of Chelsea Creek - London's most elegant new dockside development, combining luxury city living with blissful tranquillity, moments from the stylish King's Road. Located in a prime central London residential location, on the north bank of the River Thames and adjacent to fashionable Chelsea Harbour and Imperial Wharf. Chelsea Creek benefits from a 24 hour concierge and is just seconds away from Imperial Wharf Station for the train or Chelsea Harbour for the River Bus.",
        "availability_60": 1,
        "picture_url": {
          "mimetype": "image/jpeg",
          "format": "JPEG",
          "color_summary": [
            "rgba(201, 200, 204, 1.00)",
            "rgba(197, 197, 199, 1.00)",
            "rgba(175, 167, 163, 1.00)"
          ],
          "filename": "587f3361_original.jpg",
          "width": 720,
          "id": "41344729ef415c6ba38fb237b9dadd1d",
          "height": 480,
          "thumbnail": true
        },
        "zipcode": "SW6 2FL",
        "host_since": "2014-03-31",
        "host_location": "London, United Kingdom",
        "access": "Collect keys from the concierge. You can get access to the apartment after 3pm on the day of arrival, and guests need to leave by 11am on the day of departure - unless otherwise agreed with the host.",
        "availability_90": 1,
        "review_scores_value": 10,
        "thumbnail_url": "https://a0.muscache.com/im/pictures/35648182/587f3361_original.jpg?aki_policy=small",
        "amenities": "TV,Cable TV,Internet,Wireless Internet,Air conditioning,Pool,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50",
        "security_deposit": 200,
        "maximum_nights": 14,
        "host_response_time": "within an hour",
        "latitude": "51.47526359086135",
        "review_scores_location": 9,
        "house_rules": "No smoking, no children, no pets, Maximum 2 guests.",
        "monthly_price": 3250,
        "listing_url": "https://www.airbnb.com/rooms/2682093",
        "bedrooms": 1,
        "description": "Spectacular newly completed 4th floor Manhattan style luxury apartment overlooking communal gardens by Chelsea Harbour & River Thames. A good size open plan living room, double bedroom, modern kitchen & bathroom, and private balcony. A spectacular newly completed 4th floor (of five) Manhattan style apartment overlooking the quiet well maintained communal gardens designed by award-winning gardener. The accommodation offers a good size open plan living room with modern kitchen, access to a 40 square foot private balcony, a double bedroom with fitted wardrobes and en-suite shower room. This high-end apartment is part of Chelsea Creek - London's most elegant new dockside development, combining luxury city living with blissful tranquillity, moments from the stylish King's Road. Located in a prime central London residential location, on the north bank of the River Thames and adjacent to fashionable Chelsea Harbour and Imperial Wharf. Chelsea Creek benefits from a 24 hour concierge and is j",
        "review_scores_communication": 10,
        "experiences_offered": "none",
        "price": 99,
        "host_picture_url": "https://a0.muscache.com/im/users/13731005/profile_pic/1396273319/original.jpg?aki_policy=profile_x_medium",
        "extra_people": 0,
        "smart_location": "London, United Kingdom",
        "weekly_price": 840,
        "last_review": "2017-01-02",
        "host_verifications": "email,phone,reviews,jumio",
        "number_of_reviews": 33,
        "host_response_rate": 100,
        "minimum_nights": 5,
        "host_about": "I am from London and spend most of my spare time visiting art galleries and restaurants. I am the co-owner of London's boutique photography gallery The Little Black Gallery ((URL HIDDEN) When I am not in London I am enjoying life at my home in the Tarn in France.",
        "guests_included": 1,
        "host_url": "https://www.airbnb.com/users/show/13731005",
        "host_id": "13731005",
        "availability_30": 1,
        "host_total_listings_count": 1,
        "neighbourhood": "Sands End",
        "calculated_host_listings_count": 1,
        "interaction": "I am available via email & or telephone. Any problems then the housekeeper or handy man can be contacted or visit.",
        "name": "Luxury apartment in Chelsea Creek",
        "neighbourhood_cleansed": "Hammersmith and Fulham",
        "bed_type": "Real Bed",
        "host_listings_count": 1,
        "notes": "The apartment includes a double-bed, wardrobe & hanging facilities, fridge, freezer, dishwasher, washing machine & dryer, iron & ironing board. Free Sky TV and Wifi. (Please note this is my London home - so my clothes are stored in the wardrobes. Please bring your own international chargers as none are left in the apartment. Your possessions are not covered by my insurance so please make sure you have travel insurance). I am afraid There is NO access to the Gym & Spa for guests.",
        "longitude": "-0.18427740690654582",
        "summary": "Spectacular newly completed 4th floor Manhattan style luxury apartment overlooking communal gardens by Chelsea Harbour & River Thames. A good size open plan living room, double bedroom, modern kitchen & bathroom, and private balcony.",
        "beds": 1,
        "host_thumbnail_url": "https://a0.muscache.com/im/users/13731005/profile_pic/1396273319/original.jpg?aki_policy=profile_small",
        "xl_picture_url": "https://a0.muscache.com/im/pictures/35648182/587f3361_original.jpg?aki_policy=x_large",
        "cleaning_fee": 40,
        "host_name": "Ghislain",
        "country": "United Kingdom",
        "scrape_id": "20170304065726",
        "review_scores_rating": 98,
        "review_scores_checkin": 10,
        "room_type": "Entire home/apt"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.18427740690654582,
          51.47526359086135
        ]
      },
      "record_timestamp": "2020-08-02T17:09:33.658000+00:00"
    },
    {
      "datasetid": "airbnb-listings",
      "recordid": "b0b02d48c7161340979eeb313cfcc0fcf05f518a",
      "fields": {
        "review_scores_accuracy": 9,
        "reviews_per_month": 2.06,
        "bathrooms": 1,
        "first_review": "2013-09-19",
        "geolocation": [
          51.47201900816562,
          -0.16662803044675525
        ],
        "cancellation_policy": "moderate",
        "transit": "When not on public transport (details below), I always use the Uber car service and recommend it highly. If you haven't used it before, download the app and use my referral code am9sj to get £10 off your first ride. Bus stops within 50m to take you literally anywhere in London. Chelsea and South ken are walking distance anyway, but buses to Sloane Square, Victoria, Waterloo, Notting Hill, Clapham, Brixton all very easy.",
        "accommodates": 2,
        "calendar_last_scraped": "2017-03-04",
        "medium_url": "https://a0.muscache.com/im/pictures/c43b171a-8580-4087-b1ba-6f0ff3560f09.jpg?aki_policy=medium",
        "host_neighbourhood": "Battersea",
        "street": "Battersea Park Road, London, London SW11 3BP, United Kingdom",
        "last_scraped": "2017-03-05",
        "calendar_updated": "3 days ago",
        "country_code": "GB",
        "review_scores_cleanliness": 9,
        "neighborhood_overview": "So, so much to do within walking distance. There are Italian, Spanish, Japanese, Mexican and Indian restaurants all within walking distance as well as 4 or 5 great pubs. There's even an indoor pool 150m away where you can swim for £4 a go. But Battersea Park is the real gem - 250m away from London's best park - the only one with riverside too. Lakes, cafés, woods and open spaces. Perfect for picnics if the weather is good. There's also a fantastic kids playground and adventure playground in Battersea Park.",
        "availability_365": 80,
        "id": "1520434",
        "market": "London",
        "features": "Host Is Superhost,Host Has Profile Pic,Host Identity Verified,Is Location Exact",
        "city": "London",
        "property_type": "Apartment",
        "space": "- Open fire in original Victorian brick feature fireplace - Super comfortable leather sleigh bed with memory foam mattress - Walk-in marble and glass shower with unlimited mains pressure hot water - Great music and large screen tv entertainment system including Apple TV - Vinyl Record turntable, large Tannoy speakers and a selection of records - Fully equipped kitchen, including dish washer. Shabby but homely, cosy with wooden floors, leather sofa and leather double sleigh-bed, this flat is on a noisy main road above a great Thai restaurant but in a fantastic location walking distance from many bars cafés, shops and Battersea Park by the river. The combination of wood and sea grass flooring with the leather sofa and king size leather double \"sleigh\" bed gives this flat a really warm cosy feeling which was the reason we bought it. It also has a large flat screen TV with superb surround sound system in front of the big l-shaped leather sofa, perfect for cosying up and enjoying a good mo",
        "availability_60": 49,
        "picture_url": {
          "mimetype": "image/jpeg",
          "format": "JPEG",
          "color_summary": [
            "rgba(131, 80, 65, 1.00)",
            "rgba(149, 121, 102, 1.00)",
            "rgba(122, 94, 86, 1.00)"
          ],
          "filename": "c43b171a-8580-4087-b1ba-6f0ff3560f09.jpg",
          "width": 720,
          "id": "050d715368549b21c00c9c39cdd4dc49",
          "height": 480,
          "thumbnail": true
        },
        "zipcode": "SW11 3BP",
        "host_location": "England, United Kingdom",
        "access": "Guests can use the high speed wifi network, TV, washing machine, dish washer and walk in shower. There is now also Apple TV available for streaming video from any of your own Apple devices! Just select HDMI 2 as the AV source.",
        "availability_90": 79,
        "state": "London",
        "thumbnail_url": "https://a0.muscache.com/im/pictures/c43b171a-8580-4087-b1ba-6f0ff3560f09.jpg?aki_policy=small",
        "amenities": "TV,Cable TV,Internet,Wireless Internet,Pool,Kitchen,Pets allowed,Gym,Breakfast,Indoor fireplace,Buzzer/wireless intercom,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Keypad,Lockbox",
        "security_deposit": 300,
        "maximum_nights": 14,
        "review_scores_value": 9,
        "latitude": "51.47201900816562",
        "review_scores_location": 9,
        "house_rules": "Make yourself at home and treat it as if you were staying at a friend's place. The upstairs neighbours (Delisa and her bf) are friends of mine. Please respect their peace and quiet late at night! No parties, but friends welcome for dinner or a quiet drink.",
        "host_since": "2013-04-24",
        "listing_url": "https://www.airbnb.com/rooms/1520434",
        "bedrooms": 1,
        "description": "Stunning, cosy spacious open plan flat with underheated hard wood floors, leather sofa and King Size double leather sleigh bed, this flat is on a main road above a great Thai restaurant, in a fantastic location walking distance from many bars, cafés, shops & Battersea Park London's only park by the river. Vinyl record turntable, Netflix and Apple TV system, and 24hr check in. - Open fire in original Victorian brick feature fireplace - Super comfortable leather sleigh bed with memory foam mattress - Walk-in marble and glass shower with unlimited mains pressure hot water - Great music and large screen tv entertainment system including Apple TV - Vinyl Record turntable, large Tannoy speakers and a selection of records - Fully equipped kitchen, including dish washer. Shabby but homely, cosy with wooden floors, leather sofa and leather double sleigh-bed, this flat is on a noisy main road above a great Thai restaurant but in a fantastic location walking distance from many bars cafés, shops a",
        "review_scores_communication": 10,
        "experiences_offered": "romantic",
        "price": 99,
        "host_picture_url": "https://a0.muscache.com/im/pictures/4a9473f2-ab8d-4f7e-8daa-3bd25304a3cf.jpg?aki_policy=profile_x_medium",
        "extra_people": 40,
        "smart_location": "London, United Kingdom",
        "last_review": "2017-02-05",
        "host_verifications": "email,phone,reviews,manual_offline,jumio",
        "number_of_reviews": 87,
        "host_response_rate": 100,
        "minimum_nights": 1,
        "host_about": "Hi, welcome to my profile page. I live between Devon and London and work from home (running the non techie side of a software business) most of the time. `Being fortunate enough to have two homes, one is always empty, which is a waste! So I love having Airbnb guests make the most of them instead. I have a Dalmation called Bingo who goes everywhere with me. I'm a pilot in my spare time (small planes), I play the drums, am studying the piano, and love riding my motorbike. I wish I had more time to use the pool in Devon. I can't bear losing time in traffic, so I usually drive up/down between London and Devon late in the evening.",
        "guests_included": 1,
        "host_url": "https://www.airbnb.com/users/show/6070670",
        "host_id": "6070670",
        "availability_30": 19,
        "host_response_time": "within an hour",
        "host_total_listings_count": 4,
        "neighbourhood": "Battersea",
        "calculated_host_listings_count": 1,
        "interaction": "First-time guests at short notice must call for contact and may be met on their first check in, but with a key pad entry system, you can also have total privacy with no need to meet anyone, if that's your preference. Otherwise, I'm always available by message to answer any questions.",
        "name": "Luxury Battersea home w open fire, close to Park",
        "neighbourhood_cleansed": "Wandsworth",
        "bed_type": "Real Bed",
        "host_listings_count": 4,
        "notes": "There is double glazing providing good sound proofing but the road is noisy! Just imagine you're in New York! Although I have put \"gym\" and \"pool\" available they are not in the building. They are at the \"Latchmere Centre\" 100metres walk.",
        "longitude": "-0.16662803044675525",
        "summary": "Stunning, cosy spacious open plan flat with underheated hard wood floors, leather sofa and King Size double leather sleigh bed, this flat is on a main road above a great Thai restaurant, in a fantastic location walking distance from many bars, cafés, shops & Battersea Park London's only park by the river. Vinyl record turntable, Netflix and Apple TV system, and 24hr check in.",
        "beds": 1,
        "host_thumbnail_url": "https://a0.muscache.com/im/pictures/4a9473f2-ab8d-4f7e-8daa-3bd25304a3cf.jpg?aki_policy=profile_small",
        "xl_picture_url": "https://a0.muscache.com/im/pictures/c43b171a-8580-4087-b1ba-6f0ff3560f09.jpg?aki_policy=x_large",
        "cleaning_fee": 50,
        "host_name": "Charlie",
        "country": "United Kingdom",
        "scrape_id": "20170304065726",
        "review_scores_rating": 92,
        "review_scores_checkin": 10,
        "room_type": "Entire home/apt"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.16662803044675525,
          51.47201900816562
        ]
      },
      "record_timestamp": "2020-08-02T17:09:33.658000+00:00"
    },
    {
      "datasetid": "airbnb-listings",
      "recordid": "49657479ce18ae9f47f7b2d3e0f2b6bc4ab070c5",
      "fields": {
        "review_scores_accuracy": 10,
        "reviews_per_month": 1.36,
        "bathrooms": 2,
        "first_review": "2016-12-29",
        "geolocation": [
          51.53698909403137,
          -0.12268955645916126
        ],
        "cancellation_policy": "strict",
        "transit": "The are 3 tube/rail stations very close and bus stops even closer: Kings cross International tube and rail is about than 10 minutes walk, 5 minutes on the bus cost £1.20 or in a taxi/uber cost around £5.00 Caledonia road (Piccadilly line)",
        "accommodates": 5,
        "calendar_last_scraped": "2017-03-04",
        "medium_url": "https://a0.muscache.com/im/pictures/b9af7c9f-7be2-4615-995d-4da876621a5f.jpg?aki_policy=medium",
        "host_neighbourhood": "Kings Cross",
        "street": "St Williams Court, 1 Gifford Street, London, England N1, United Kingdom",
        "last_scraped": "2017-03-04",
        "calendar_updated": "today",
        "country_code": "GB",
        "review_scores_cleanliness": 10,
        "neighborhood_overview": "Tree lined park at the front of the building and Japanese gardens with water feature at the centre of the building. World famous St Martin design college 5 minutes walk. Waitrose 5 minutes walk; superior supermarket with wine bar, cooking lessons and jazz band as you select your groceries. A few minutes walk to countless take aways, restaurants, pubs and local stores.",
        "availability_365": 258,
        "id": "13934353",
        "market": "London",
        "features": "Host Is Superhost,Host Has Profile Pic,Host Identity Verified,Is Location Exact",
        "city": "London",
        "property_type": "Apartment",
        "space": "Bedroom1 : King size master en-suite bedroom. Beautiful appointed and immaculately clean the furnishings including matching bed and bedside tables with accompanying soft glow, globe lamps. The superior comfort of the king size designer bed has the added benefit of built in roller storage spaces either side. The king size bed is dressed in 100% Egyptian cotton sheets and the luxury duvet is 100% goose down. The en suite: Within the king size master bedroom is the en suite comprising of double mirror storage, chrome fittings throughout and a double size power shower. Additionally a designer chrome leather work station can be provided and is easily accommodated. The en suite with double shower. Wall, ceiling and bedside lighting. Swish full size lined curtain opening onto a bedroom balcony overlooking a waterfall immaculately kept enormous communal garden space. Lounge: Wall and ceiling lighting plus laps. Soft leather sofa and plasma TV and DVD. floor to ceiling window with balcony a",
        "availability_60": 26,
        "picture_url": {
          "mimetype": "image/jpeg",
          "format": "JPEG",
          "color_summary": [
            "rgba(189, 165, 129, 1.00)",
            "rgba(134, 113, 102, 1.00)",
            "rgba(69, 41, 37, 1.00)"
          ],
          "filename": "b9af7c9f-7be2-4615-995d-4da876621a5f.jpg",
          "width": 639,
          "id": "06704371a5ea1181dc56884277001054",
          "height": 426,
          "thumbnail": true
        },
        "zipcode": "N1",
        "host_location": "London, England, United Kingdom",
        "access": "Access to the all the apartment, utilities and extended facilities: Bedrooms, en suite, Bathroom, lounge, kitchen, dinning room, balcony x 2 garden, park, car park, bike storage, reception, gym, sauna, steam room etc",
        "availability_90": 55,
        "state": "England",
        "thumbnail_url": "https://a0.muscache.com/im/pictures/b9af7c9f-7be2-4615-995d-4da876621a5f.jpg?aki_policy=small",
        "amenities": "TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Pool,Kitchen,Free parking on premises,Doorman,Gym,Breakfast,Elevator in building,Hot tub,Indoor fireplace,Buzzer/wireless intercom,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry,Private entrance",
        "security_deposit": 450,
        "maximum_nights": 1125,
        "review_scores_value": 10,
        "latitude": "51.53698909403137",
        "review_scores_location": 10,
        "house_rules": "Maid/butler/chauffeur (negotiable additional service) available upon request. All guest agree to adhere to apartment complex rules and regulation at all times. Detailed list available upon demand and signed before checking in.",
        "host_since": "2016-03-05",
        "listing_url": "https://www.airbnb.com/rooms/13934353",
        "bedrooms": 2,
        "description": "Perfect central London location with the feeling a tranquility Sauna, steam room, full size gym & car park Bedroom 1. Luxury master bedroom, en-suite shower room Bedroom 2. Luxury double bedroom with private bathroom Each bedroom overlooks the Japanese water fountain garden Both bedrooms with access to the double garden balcony Light spacious lounge access to double park view balcony 4 seating dinning area with access to the front balcony Ultra modern fully equipped open plan kitchen Bedroom1 : King size master en-suite bedroom. Beautiful appointed and immaculately clean the furnishings including matching bed and bedside tables with accompanying soft glow, globe lamps. The superior comfort of the king size designer bed has the added benefit of built in roller storage spaces either side. The king size bed is dressed in 100% Egyptian cotton sheets and the luxury duvet is 100% goose down. The en suite: Within the king size master bedroom is the en suite comprising of double mirror s",
        "review_scores_communication": 10,
        "experiences_offered": "none",
        "price": 125,
        "host_picture_url": "https://a0.muscache.com/im/pictures/4697991b-9ca3-4d08-92b5-f5c429227d3c.jpg?aki_policy=profile_x_medium",
        "extra_people": 49,
        "smart_location": "London, United Kingdom",
        "last_review": "2017-03-01",
        "host_verifications": "email,phone,reviews,jumio,government_id",
        "number_of_reviews": 3,
        "host_response_rate": 100,
        "minimum_nights": 1,
        "host_response_time": "within an hour",
        "guests_included": 4,
        "host_url": "https://www.airbnb.com/users/show/61664856",
        "host_id": "61664856",
        "availability_30": 9,
        "host_total_listings_count": 2,
        "neighbourhood": "Kings Cross",
        "calculated_host_listings_count": 2,
        "interaction": "Always available and happy to help with anything you might need.",
        "name": "2 Bedroom Luxury Apartment: Sauna Steam room & Gym",
        "neighbourhood_cleansed": "Camden",
        "bed_type": "Real Bed",
        "host_listings_count": 2,
        "notes": "Smoking is permitted on either balcony only with the balcony door fully closed please, thank you!",
        "longitude": "-0.12268955645916126",
        "summary": "Perfect central London location with the feeling a tranquility Sauna, steam room, full size gym & car park Bedroom 1. Luxury master bedroom, en-suite shower room Bedroom 2. Luxury double bedroom with private bathroom Each bedroom overlooks the Japanese water fountain garden Both bedrooms with access to the double garden balcony Light spacious lounge access to double park view balcony 4 seating dinning area with access to the front balcony Ultra modern fully equipped open plan kitchen",
        "beds": 2,
        "host_thumbnail_url": "https://a0.muscache.com/im/pictures/4697991b-9ca3-4d08-92b5-f5c429227d3c.jpg?aki_policy=profile_small",
        "xl_picture_url": "https://a0.muscache.com/im/pictures/b9af7c9f-7be2-4615-995d-4da876621a5f.jpg?aki_policy=x_large",
        "cleaning_fee": 30,
        "host_name": "Carl & Elodie",
        "country": "United Kingdom",
        "scrape_id": "20170304065726",
        "review_scores_rating": 100,
        "review_scores_checkin": 10,
        "room_type": "Entire home/apt"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.12268955645916126,
          51.53698909403137
        ]
      },
      "record_timestamp": "2020-08-02T17:09:33.658000+00:00"
    }
  ]

}