// Generated by https://quicktype.io

export interface PropertyResults {
  datasetid: Datasetid;
  recordid: string;
  fields: Fields;
  geometry: Geometry;
  record_timestamp: string;
}

export enum Datasetid {
  AirbnbListings = "airbnb-listings",
}

export interface Fields {
  review_scores_accuracy?: number;
  reviews_per_month?: number;
  bathrooms: number;
  first_review?: string;
  geolocation: number[];
  cancellation_policy: CancellationPolicy;
  transit?: string;
  accommodates: number;
  neighbourhood_cleansed: string;
  host_neighbourhood?: string;
  street: string;
  review_scores_communication?: number;
  calendar_updated: string;
  country_code: CountryCode;
  review_scores_cleanliness?: number;
  property_type: PropertyType;
  availability_365: number;
  id: string;
  market: City;
  features: string;
  city: City;
  space?: string;
  availability_60: number;
  picture_url?: PictureURL;
  calendar_last_scraped: string;
  host_location: string;
  access?: string;
  availability_90: number;
  state?: City;
  amenities: string;
  host_listings_count: number;
  maximum_nights: number;
  listing_url: string;
  latitude: string;
  review_scores_location?: number;
  house_rules?: string;
  host_since: string;
  bedrooms: number;
  description: string;
  experiences_offered: ExperiencesOffered;
  price: number;
  host_picture_url: string;
  extra_people: number;
  smart_location: SmartLocation;
  last_review?: string;
  host_verifications: string;
  number_of_reviews: number;
  host_response_rate: number;
  minimum_nights: number;
  host_about?: string;
  guests_included: number;
  host_url: string;
  host_id: string;
  availability_30: number;
  host_total_listings_count: number;
  calculated_host_listings_count: number;
  interaction?: string;
  name: string;
  bed_type: BedType;
  country: Country;
  host_response_time: HostResponseTime;
  longitude: string;
  summary?: string;
  beds: number;
  host_thumbnail_url: string;
  review_scores_value?: number;
  host_name: string;
  last_scraped: string;
  scrape_id: string;
  review_scores_rating?: number;
  review_scores_checkin?: number;
  room_type: RoomType;
  medium_url?: string;
  neighborhood_overview?: string;
  zipcode?: string;
  thumbnail_url?: string;
  security_deposit?: number;
  monthly_price?: number;
  neighbourhood?: string;
  notes?: string;
  xl_picture_url?: string;
  weekly_price?: number;
  cleaning_fee?: number;
  square_feet?: number;
}

export enum BedType {
  RealBed = "Real Bed",
}

export enum CancellationPolicy {
  Flexible = "flexible",
  Moderate = "moderate",
  Strict = "strict",
}

export enum City {
  England = "England",
  GreaterLondon = "Greater London",
  London = "London",
}

export enum Country {
  UnitedKingdom = "United Kingdom",
}

export enum CountryCode {
  GB = "GB",
}

export enum ExperiencesOffered {
  Business = "business",
  Family = "family",
  None = "none",
  Romantic = "romantic",
}

export enum HostResponseTime {
  WithinAnHour = "within an hour",
}

export interface PictureURL {
  mimetype: Mimetype;
  format: Format;
  color_summary: string[];
  filename: string;
  width: number;
  id: string;
  height: number;
  thumbnail: boolean;
}

export enum Format {
  JPEG = "JPEG",
}

export enum Mimetype {
  ImageJPEG = "image/jpeg",
}

export enum PropertyType {
  Apartment = "Apartment",
}

export enum RoomType {
  EntireHomeApt = "Entire home/apt",
}

export enum SmartLocation {
  LondonUnitedKingdom = "London, United Kingdom",
}

export interface Geometry {
  type: Type;
  coordinates: number[];
}

export enum Type {
  Point = "Point",
}
